### ISSUE TITLE
Define and enforce MSRV

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#1]
Looks like the crate depends on fairly fresh compiler features:
> error[E0277]: arrays only have std trait implementations for lengths 0..=32
  --> /Users/dmalyshau/.cargo/git/checkouts/gpu-alloc-b89b27c43ff2846f/0bdf9ea/gpu-alloc/src/usage.rs:51:5
   |
51 |     usages: [MemoryForOneUsage; 64],
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::array::LengthAtMost32` is not implemented for `[usage::MemoryForOneUsage; 64]`
   |
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `[usage::MemoryForOneUsage; 64]`
   = note: required because of the requirements on the impl of `std::fmt::Debug` for `&[usage::MemoryForOneUsage; 64]`
   = note: required for the cast to the object type `dyn std::fmt::Debug`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info

**Comment by zakarumych** [comment]
MSRV is 1.40
And 1.46 for `gpu-alloc-erupt`
