### ISSUE TITLE
Merge Strategy into Request

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#10]
I think something like this would make sense:
```rust
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum RequestStrategy {
    Implicit(Dedicated),
    Explicit(Strategy),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Request {
    pub size: u64,
    pub align: u64,
    pub memory_types: u32,
    pub usage: UsageFlags,
    pub strategy: RequestStrategy,
}
```

That would make it so you don't have to specify the usage flags and stuff when you know the strategy, and you don't need an extra `alloc_with_strategy` method.

**Comment by zakarumych** [comment]
I'd like to keep easy method without complex arguments.
'Dedicated' argument can be removed from 'alloc_with_strategy'.

And maybe another method without either 'Dedicated' or 'Strategy' arguments?

**Comment by zakarumych** [comment]
UsageFlags are still required for all those methods

**Comment by kvark** [comment]
So basically it's either Dedicated, Strategy, or neither (which presumably be the same as `Dedicated::default()`)?

**Comment by zakarumych** [comment]
Yes.
