### ISSUE TITLE
EruptMemoryDevice missing `Clone` impl

### ISSUE THREAD

**Issue by Masterchef365** [zakarumych/gpu-alloc#20]
I get `trait bound erupt::DeviceLoader: std::clone::Clone is not satisfied` when trying to use the following: 
```rust
let block = unsafe { allocator.alloc(EruptMemoryDevice::wrap(&core.device), request)? };
```
Guessing the `M: Clone` trait bound was added to `alloc(...)` after the erupt backend was written?
(More context if you need it [here](https://github.com/Masterchef365/TensorSludge/blob/allocator_port/src/matrix.rs#L63))

**Comment by zakarumych** [comment]
`M` is parameter for memory handle, not device.
For erupt you should use `erupt::vk1_0::DeviceMemory`.
For example `gpu_alloc::MemoryBlock<erupt::vk1_0::DeviceMemory>`, `GpuAllocator<erupt::vk1_0::DeviceMemory>`

`EruptMemoryDevice` is transparent wrapper around `erupt::DeviceLoader` to implement foreign trait for it.
Note that `EruptMemoryDevice::wrap` takes and returns a reference.

**Comment by Masterchef365** [comment]
Ah I see, that wasn't terribly clear from the API docs. I see that there's now an example for it; I'll reference that. Thanks!

**Comment by zakarumych** [comment]
> that wasn't terribly clear from the API docs

Noted.
