### ISSUE TITLE
Disregarded semver

### ISSUE THREAD

**Issue by LU15W1R7H** [zakarumych/gpu-alloc#39]
The last release `gpu-alloc 0.3.1` introduced a breaking change and therefore didn't adhere to semantic versioning.

As a result cargo automatically uses the new version (if `Cargo.lock` is recent)  and previously working code breaks.

The breaking change lies in fixing a typo (treshold => threshold) in `src/config.rs`.

`wgpu-core`, which uses `gpu-alloc`, no longer compiles (see gfx-rs/wgpu#1285).

**Comment by zakarumych** [comment]
0.3.1 has been yanked.

**Comment by LU15W1R7H** [comment]
Thank you. This fixed it :).
