### ISSUE TITLE
Explicit allocator kind request

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#4]
One thing that we had in `gfx-memory` that worked exceptionally well was that the user explicitly selected what kind of allocator was needed: https://docs.rs/gfx-memory/0.2.2/gfx_memory/struct.Heaps.html#method.allocate

So `wgpu` knows precisely when it needs a generic allocation versus the linear allocation. With rendy-memory as well as gpu-alloc as it's successor, this becomes a guessing game: what `UsageFlags` do I need to specify in order for the allocator to pick the proper sub-allocator kind? I believe this is a totally useless indirection. The API should be explicit about linear/general/dedicated allocation, and only default to dedicated if the other one fails.

As it stands now, I consider this a blocker for `wgpu` integration. It's very important for us to know what sub-allocator is involved.

**Comment by zakarumych** [comment]
Thank you for your suggestion.

The point of `GpuAllocator` is to decide on which kind of sub-allocation to perform. It should be enough for user to specify intended usage, I'm almost sure that `wgpu` makes decision based on usage and size, exactly how `GpuAllocator` does it.
So if `wgpu` does this better - maybe it would be better to simply move wgpu's decision algorithm to `gpu-alloc`?

**Comment by kvark** [comment]
> So if wgpu does this better - maybe it would be better to simply move wgpu's decision algorithm to gpu-alloc?

If `wgpu` does this better - then `gpu-alloc` shouldn't take this responsibility at all. It's not essential for this crate to do this guess work. The core of it, as I see it, is the exact mamory allocation algorithms. If the guesswork / decision making can be moved out to user space, then it should be.

**Comment by zakarumych** [comment]
Maybe, but one can end up with situation that user does decision worse while thinking it does better.

**Comment by zakarumych** [comment]
The purpose of the crate is to make user think less about memory allocation unless some memory shenanigans are required for optimization purposes when no provided sub-allocator would work well.

**Comment by kvark** [comment]
> Maybe, but one can end up with situation that user does decision worse while thinking it does better.

There is no need for this library to be opinionated and try being smarter than the user. It's totally in the way for `wgpu`, which doesn't want to "hint" but instead control what kind of allocations are done. If you find it useful to other users, you can have a low-level API where one selects the allocator kind, and then a higher level API that helps choosing one based on some criteria.

**Comment by zakarumych** [comment]
The only reason I'm against low-level API with sub-allocation kind in parameter is because I'd prefer keep sub-allocation as implementation details. To be able to add or remove them or change behavior. Without concern of the end user.

I understand your point. Which is totally valid if wgpu has a way to be smarter than the allocator. And I'd like to know, is there one?

**Comment by kvark** [comment]
> To be able to add or remove them or change behavior. Without concern of the end user.

You can still have high level hint API that some users would prefer, to alleviate this.

> I understand your point. Which is totally valid if wgpu has a way to be smarter than the allocator.

I don't think you understand in full. It's not even about being smarter than the allocator. It's the weird need to reverse-engineer the allocator in canse we *know* what we need. And `wgpu` tries to know very well what it needs, in order to reason about the performance. This reasoning is even influencing the spec (e.g. "we can use linear allocation with this kind of API").

> And I'd like to know, is there one?

Here is the logic:
  1. for staging data, use linear allocator
  2. for everything else, use generic allocator

**Comment by zakarumych** [comment]
> Here is the logic:
>
> 1. for staging data, use linear allocator
> 2. for everything else, use generic allocator

It's not about reverse-engineering, but not doing logic at all. Just tell allocator that you intend to deallocate soon - e.g. memory usage is transient.

You can think in the same manner that you want to manually specify what memory type properties are required and what should be avoided. But you don't, are you?

> You can still have high level hint API that some users would prefer, to alleviate this.

But sub-allocators will be public, I won't be able to quietly add and remove them, or change behavior in such a way that your assumption when to use specific sub-allocator rendered invalid.

**Comment by kvark** [comment]
> Just tell allocator that you intend to deallocate soon - e.g. memory usage is transient.

Semantically, this is a hint in the API of this library. It makes us second-guess "are we really using that allocation strategy here?". Also, it's a weaker hint than what we often have "I'm going to free this strictly after I free all the previous allocations in this heap".

> You can think in the same manner that you want to manually specify what memory type properties are required and what should be avoided. But you don't, are you?

It's not a far stretch to imagine us dictating this as well. Some libraries just need more control, you know?

> But sub-allocators will be public, I won't be able to quietly add and remove them, or change behavior in such a way that your assumption when to use specific sub-allocator rendered invalid.

Are you planning on adding or removing sub-allocators in non-API-breaking changes in the future? Your prior art - rendy-memory - didn't appear to need to add or remove those through its lifetime.

Since you feel strongly about hiding the notion of sub-allocators in this library, I suppose one way to compromise is exposing them to us *directly*. So you could move the logic of a buddy allocator into some `gpu-alloc-buddy` crate, and the same for the linear allocator. You'd use these in `gpu-alloc`, and we'd use them directly in `wgpu`.

**Comment by zakarumych** [comment]
> > You can think in the same manner that you want to manually specify what memory type properties are required and what should be avoided. But you don't, are you?
>
> It's not a far stretch to imagine us dictating this as well. Some libraries just need more control, you know?

If wgpu developers would find some arcane knowledge that allows to better pick an allocation strategy and/or memory type for particular use-case - I would kindly ask you to introduce this idea to `gpu-alloc` :)

> Since you feel strongly about hiding the notion of sub-allocators in this library, I suppose one way to compromise is exposing them to us directly

That's one possible solution. On the other hand, adding new sub-allocators with minor version change should be ok, while removing in dramatically changing behavior is not really needed. Instead new replacement allocation strategy can be added and old one left soft-deprected until next major release.

**Comment by zakarumych** [comment]
Fixed in #7
