### ISSUE TITLE
Option to silence errors sent to stderr

### ISSUE THREAD

**Issue by francesco-cattoglio** [zakarumych/gpu-alloc#41]
I have written a program that uses wgpu, and if a panic occurs I get a lot of error messages from gpu-alloc, due to this line:

https://github.com/zakarumych/gpu-alloc/blob/2baf6a9f7b3a9f39a5b0a132cd277eb3c0666a5e/gpu-alloc/src/block.rs#L23

Due to the high amount of messages that gpu-alloc prints, trying to understand what caused the panic in the first place can be tricky. This can be especially annoying when the console output moves previous messages so far up that they no longer show.

Do you think it might be possible to add some option to suppress or remove that output?

**Comment by zakarumych** [comment]
I think with `std` enabled it should not print those messages when unwinding happens.
