### ISSUE TITLE
Assertion failed: Greater == Equal

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#46]
Created from https://github.com/gfx-rs/wgpu/issues/1364

> Panic Payload: "assertion failed: (left == right)\n left: Greater,\n right: Equal"
PanicInfo: panicked at 'assertion failed: (left == right)
left: Greater,
right: Equal', /Users/bronson/.cargo/registry/src/github.com-1ecc6299db9ec823/gpu-alloc-0.4.4/src/freelist.rs:201:9

Repro steps:
```bash
# download and unpack trace-cross.zip
# add "]" to the end
# s/Metal/Vulkan/g (assuming you are on Vulkan?)
git clone https://github.com/gfx-rs/wgpu
cd wgpu/player
cargo run --features winit,cross -- <path to unpacked trace>
```

Edit: actually, the repro case doesn't work for me.

**Comment by zakarumych** [comment]
The problem was caused by invalid assert. Patch published.
