### ISSUE TITLE
Leaked memory on v0.4

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#48]
Updating `wgpu` from gpu-alloc 2cd1ad650cdd24d1647b6041f77ced0cbf1ff2a6 to 0.4 started to result in vulkan validation errors, see https://github.com/gfx-rs/wgpu/issues/1404. It can be reproduced by just checking out `wgpu` and running `cargo test` (on Linux with Vulkan support). Any idea what this might be caused by?

**Comment by zakarumych** [comment]
There was a problem with merging tail block in its region to others, and they were not deallocated on cleanup.
Patch is already on crates.io

**Comment by kvark** [comment]
Thank you for the quick fix!
