### ISSUE TITLE
Transient on windows allocates 130mb of memory

### ISSUE THREAD

**Issue by Dispersia** [zakarumych/gpu-alloc#50]
Hello, as title says on windows, transiest allocates 130mb of memory the first time it is called.

 Using my example from https://github.com/gfx-rs/wgpu/issues/1407:
 https://github.com/zakarumych/gpu-alloc/blob/12c138efc80f5f6d509a76eedaa92e821afe436a/gpu-alloc/src/allocator.rs#L255
 
 Strategy::{FreeList, Linear} both cause this behavior, but changing it to Dedicated or Buddy does not. This behavior is also not observed on linux, if any other information is needed please let me know, thanks

**Comment by zakarumych** [comment]
This is expected, but, I guess, undesired behavior.

Allocating memory object is slow and costly operation. That's why gpu-alloc preallocates large enough chunks and then cheaply dispenses regions of requested sizes. Chunk sizes can be configured when creating allocator instance.

It's hard for gpu-alloc to predict that whole chunk won't be used.

For Buddy strategy, chunk size grows. It starts very small and, roughly speaking, doubled for new chunks.

Maybe similar idea can be used for FreeList strategy.
I will look into it.

**Comment by zakarumych** [comment]
I've made it so free list chunks grow from one configured value to another.

For default prototyping config it will be 8Mb and 128Mb, so if application never needs more than, say, 16Mb at a time, then `gpu-alloc` will allocate 8Mb chunk first, then 16Mb chunk, then free 8Mb chunk after last block from it is deallocated and keep reusing 16Mb chunk.

Anyone concerned can try this change before release [via patch in their crate's manifest](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html).

**Comment by kvark** [comment]
That sounds interesting, thank you for prototyping this!

**Comment by zakarumych** [comment]
I currently try to figure out best way to prevent constant memory usage allocation - deallocation if usage would flap around deallocation threshold.
I guess the easy way would be to check max usage over some reasonable window (in time or number of calls).

**Comment by Dispersia** [comment]
Correct me if I'm wrong, but isn't the general idea of staging belt in wgpu to do basically this? Could it not be used, and it's drop be the time its deallocated?

**Comment by parasyte** [comment]
FWIW, I patched `wgpu` 0.9 to use the current `gpu-alloc` and the memory usage on my app is identical. This is largely because `wgpu` uses transient allocations for things like `Queue::write_texture()`, and these transient allocations can be very large. For that reason, I kept the minimum chunk size at 128 MB.

```diff
diff --git a/wgpu-core/Cargo.toml b/wgpu-core/Cargo.toml
index 41b3f589..8ffcf6e7 100644
--- a/wgpu-core/Cargo.toml
+++ b/wgpu-core/Cargo.toml
@@ -36,7 +36,7 @@ serde = { version = "1.0", features = ["serde_derive"], optional = true }
 smallvec = "1"
 thiserror = "1"

-gpu-alloc = "0.4"
+gpu-alloc = { path = "../../gpu-alloc/gpu-alloc" }
 gpu-descriptor = "0.1"

 hal = { package = "gfx-hal", version = "0.9" }
diff --git a/wgpu-core/src/device/alloc.rs b/wgpu-core/src/device/alloc.rs
index 5366126a..b19d9a99 100644
--- a/wgpu-core/src/device/alloc.rs
+++ b/wgpu-core/src/device/alloc.rs
@@ -18,7 +18,8 @@ impl<B: hal::Backend> MemoryAllocator<B> {
             dedicated_threshold: 32 << 20,
             preferred_dedicated_threshold: 8 << 20,
             transient_dedicated_threshold: 128 << 20,
-            linear_chunk: 128 << 20,
+            starting_free_list_chunk: 128 << 20,
+            final_free_list_chunk: 1 << 30,
             minimal_buddy_size: 1 << 10,
             initial_buddy_dedicated_size: 8 << 20,
         };
```

There are also some stray `dbg!()` calls. :P

```
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:288] self.final_free_list_chunk = 1073741824
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:289] self.starting_free_list_chunk = 134217728
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:290] self.transient_dedicated_threshold = 134217728
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:291] heap.size() / 32 = 535471104
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:298] starting_free_list_chunk = 134217728
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\allocator.rs:299] final_free_list_chunk = 535471104
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\freelist.rs:433] "Allocated memory of size" = "Allocated memory of size"
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\freelist.rs:433] self.chunk_size = 134217728
```

And it gets freed when the app is closed:

```
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\freelist.rs:486] "Freed memory of size" = "Freed memory of size"
[C:\Users\jay\other-projects\gpu-alloc\gpu-alloc\src\freelist.rs:486] size = 134217728
```

This is probably ok in my case, since I call `write_texture()` on every frame. The only downside is paying the full price of admission (128 MB) even when my textures are less than 1 MB.

**Comment by zakarumych** [comment]
`starting_free_list_chunk` could be smaller than that. For example "defaults" provided by `gpu-alloc` crate sets it to 8MB.

**Comment by zakarumych** [comment]
@

**Comment by zakarumych** [comment]
@parasyte I've re-read your comment and find out that something was preventing you to use small value for `starting_free_list_chunk`. Commit above shall fix the issue.

**Comment by parasyte** [comment]
@zakarumych Thanks for addressing that! I was unsure if the debug assertion was accurate. But it was indeed preventing me from using a smaller starting chunk size.

With the latest changes, I have adjusted my wgpu patch to use 8 KB starting chunk size (even though you recommended 8 MB, _and_ my initial texture size requires a 512 KB chunk) and final chunk size of 128 MB. My most simple app now uses only about 33 MB of memory in total, and I can still use absurdly large textures like `7,760x1,440` for double-ultra-wide displays!

With 8 MB starting chunk size, memory usage is still completely reasonable in my case, ~40 MB. This is down from 160 MB total before integrating your work.

Updated `wgpu` patch is:

```patch
diff --git a/wgpu-core/src/device/alloc.rs b/wgpu-core/src/device/alloc.rs
index 5366126a..4b7c3e3d 100644
--- a/wgpu-core/src/device/alloc.rs
+++ b/wgpu-core/src/device/alloc.rs
@@ -18,7 +18,8 @@ impl<B: hal::Backend> MemoryAllocator<B> {
             dedicated_threshold: 32 << 20,
             preferred_dedicated_threshold: 8 << 20,
             transient_dedicated_threshold: 128 << 20,
-            linear_chunk: 128 << 20,
+            starting_free_list_chunk: 8 << 20,
+            final_free_list_chunk: 128 << 20,
             minimal_buddy_size: 1 << 10,
             initial_buddy_dedicated_size: 8 << 20,
         };
```

**Comment by zakarumych** [comment]
This assertion was accurate when chunk size was fixed.

As device memory allocations are very far from cheap, 8Kb starting chunk is too small.

For example, if you will upload 64mb of data each frame using many small blocks, it will grow chunk size from 8kb to 64mb and allocate 14 times. Each allocation will take significant time, but worst of all is this:
implementation may limit available number of allocations to mere dozens and it is possible to deplete this limit with those small allocations making next allocation fail, at which point your app will panic and terminate.

**Comment by zakarumych** [comment]
I believe this problem was fixed a while ago.
@parasyte is the problem still occur?

**Comment by parasyte** [comment]
IFAIK, this appears to be solved in `gpu-alloc` now. We do need the crate updated in `wgpu`, which means `gpu-alloc` still needs a new release.

**Comment by zakarumych** [comment]
It seems that `wgpu` uses latest `gpu-alloc`, so this can be closed. Reopen if you feel otherwise.
