### ISSUE TITLE
Update gpu-alloc-ash to be compatible with ash 0.37.0

### ISSUE THREAD

**Issue by realandrew** [zakarumych/gpu-alloc#58]
I'm using gpu-alloc for the first time and it seems gpu-alloc-ash needs updated to support ash 0.37.0. The `device_properties` function gives the following error
```
mismatched types
expected reference `&ash::instance::Instance`
found reference `&ash::Instance`
perhaps two different versions of crate `ash` are being used?
```
(and a similar error for the physical_device parameter) and indeed I can see the last release supported up to 0.36.0 which does have those types instead.

**Comment by zakarumych** [comment]
Yes, this happens when different versions of crate are used.
I've published `gpu-alloc-ash v0.5` that uses `ash 0.37`.
