### ISSUE TITLE
Allow adding MemoryBlocks manually to GpuAllocator

### ISSUE THREAD

**Issue by i509VCB** [zakarumych/gpu-alloc#60]
When importing external memory I need to use facilities outside of a memory device and the gpu allocator to create the device memory. Generally via extensions like VK_EXT_external_memory_dmabuf and etc.

Once I have imported the memory I would like a way to have the allocator track the external memory I have imported so that cleanup can manage freeing the allocations from external memory.

I guess a way to know how many allocations are left would also be needed to use said api safely.

**Comment by zakarumych** [comment]
This sounds reasonable and doable.
Do you want to give externally allocated memory objects or just slices of them to the `GpuAllocator`?

**Comment by i509VCB** [comment]
Well it depends if we want external memory blocks to be solely dedicated or not. If we assume dedicated blocks only I'd probably just add a function to let the GpuAllocator track a specific dedicated allocation and then decrease the remaining allocations count.

**Comment by zakarumych** [comment]
So what tracking it should do apart from number of memory object allocations?
