### ISSUE TITLE
impl Debug for GpuAllocator

### ISSUE THREAD

**Issue by kvark** [zakarumych/gpu-alloc#9]
Implementing Debug is in the Rust guidelines for public types.

**Comment by kvark** [comment]
Note: this is no longer a blocker, we wrap the type anyway and can custom impl Debug

**Comment by zakarumych** [comment]
Not any type can have useful `Debug` implementation.
Printing whole internal state would just pollute any log output.
There is not much useful info aside from it.

`GpuAllocator` will support querying usage statistics as separate functions.
It would be possible to print some of the statistics in `wgpu` wrapper's `Debug` impl.

**Comment by zakarumych** [comment]
Implemented
